name: sleep_analysis
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python == 3.6.*"
- numpy
- "pandas == 0.25.3"
- scipy
- matplotlib
- seaborn
- tqdm
- xarray
- scikit-image
- scikit-learn
- dask
- "trajectory_analysis_tools == 0.3.0.dev0"
- loren_frank_data_processing
- "ripple_detection == 0.1.8.dev0"
- "replay_trajectory_classification == 0.7.7.dev0"
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- pip
- pip:
  - "UpSetPlot==0.3.0"
  - nb-black
